spring:
  datasource:
    url: jdbc:mysql://39.100.39.63:3306/content_center
    hikari:
      username: root
      password: abc123
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ

  application:
    # 服务名称尽量使用-，不要使用_，更不要使用特殊字符
    name: content-center
server:
  port: 8010


# 当内容中心调用用户中心时，会使用RandomRule
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 开启ribbon的饥饿加载，为内容中心请求用户中心开启饥饿加载
ribbon:
  eager-load:
    clients: user-center
    enabled: true