spring:
  datasource:
    url: jdbc:mysql://39.100.39.63:3306/content_center
    hikari:
      username: root
      password: abc123
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ

    sentinel:
      filter:
        # 开启掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel控制台的地址
        dashboard: localhost:8080
        client-ip: 127.0.0.1

  application:
    # 服务名称尽量使用-，不要使用_，更不要使用特殊字符
    name: content-center

  main:
    allow-bean-definition-overriding: true
server:
  port: 8010


# 当内容中心调用用户中心时，会使用RandomRule
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 开启ribbon的饥饿加载，为内容中心请求用户中心开启饥饿加载
ribbon:
  eager-load:
    clients: user-center
    enabled: true



# 配置日志级别
logging:
  level:
    com.itcrazy.contentcenter.feignclient.UserCenterFeignClient: debug


# feign日志配置文件方式
feign:
  # 为feign整合sentinel
  sentinel:
    enabled: true
  client:
    config:
      # 想要调用微服务的名称
      default:
        loggerLevel: full
  # 让feign使用apache httpclient做请求，而不是默认的urlconnection
  httpclient:
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

#  okhttp:
#    enabled: true

# sentinel端点默认是隐藏的，需要加上配置才能显示出来
management:
  endpoints:
    web:
      exposure:
        include: '*'

#resttemplate:
#  sentinel:
#    enabled: false